#!/bin/sh

export PATH="$PATH:/usr/lib/git-encrypt"

BACKUPPATH=$1
LOCALPATH=$2


if [ "$BACKUPPATH" = "" ] ; then
  echo "Missing backup path"
  exit
fi
if [ "$LOCALPATH" = "" ] ; then
  echo "Missing local path"
  exit
fi

git clone $BACKUPPATH $LOCALPATH

cd $LOCALPATH
git-crypt unlock

