#!/bin/sh

export PATH="$PATH:/usr/lib/git-encrypt"

rsync -a -v -u /var/lib/gitolite3/ /var/lib/backup-gitolite/gitolite3


cd /var/lib/backup-gitolite/gitolite3

git add *
git add */.*
git commit -m "Regular commit"
NOTHING=$?

if [ "$NOTHING" = "0" ] ; then
  git push origin master
fi
