#!/bin/bash

#Script for keeping to git repos in a gitolite setup in sync

export PATH="$PATH:/usr/lib/gitolite-backup-scripts/git-encrypt"
source /etc/gitolite-backup-scripts.conf

BACKUPPATH=$1
LOCALPATH=$2


if [ "$BACKUPPATH" = "" ] ; then
  echo "Missing backup path"
  exit
fi
if [ "$LOCALPATH" = "" ] ; then
  echo "Missing local path"
  exit
fi

if [ -d $LOCALPATH ] ; then
  echo "Already cloned"
  pushd $LOCALPATH
   git pull origin master
  popd
else
  get_backup_gitolite $BACKUPPATH $LOCALPATH
fi

mkdir -p /tmp/gitolite_keep_in_sync
cd /tmp/gitolite_keep_in_sync

REPOS=`ls ${LOCALPATH}/repositories`

mkdir -p from to


for REPO in $REPOS;
do echo $REPO
  CONTINUE=1
  if [ "$REPO" = "gitolite-admin.git" ] ; then
    continue
  fi
  if [ -d from/$REPO ] ; then
    echo "from/$REPO is already cloned"
    pushd from/$REPO
    git pull origin master
    popd
  else
    git clone $LOCALPATH/repositories/$REPO from/$REPO
    if [ "$?" = "0" ]; then
      CONTINUE=1
    else
      CONTINUE=0
    fi
  fi
  if [ "$CONTINUE" = "1" ] ; then
    if [ -d to/$REPO ] ; then
      echo "to/$REPO is already cloned"
      pushd to/$REPO
      git pull origin master
      popd
    else
      git clone $GITOLITEUSER@localhost:$REPO to/$REPO
    fi
  fi
done


REPOS=`ls /tmp/gitolite_keep_in_sync/to`

for REPO in $REPOS;
do
 echo $REPO
 pushd /tmp/gitolite_keep_in_sync/to/$REPO
 git remote rm fromrepo
 git remote add fromrepo file:///tmp/gitolite_keep_in_sync/from/$REPO
 git pull fromrepo master
 git push origin master
 popd

done
