#!/bin/bash

export PATH=$PATH:/usr/lib/gitolite-backup-scripts/bin

CURRENTUSER=`whoami`

if [ "$CURRENTUSER" != "root" ] ;
then
    echo "It needs to be run as root!"
    exit -1
fi

if [ "$1" = "" ] ; then
    echo "Missing argument"
    exit -1
fi



pushd /var/lib

mv gitolite3 gitolite3.old
pushd  /var/lib/backup-gitolite


mv gitolite3 gitolite3.old
get_backup_gitolite $1 gitolite3
chown -R gitolite3:gitolite3 gitolite3
chmod -R go-rwx gitolite3
chmod go+rx gitolite3

cp -r gitolite3 ../ 

popd

chown -R gitolite3:gitolite3 gitolite3
chmod -R go-rwx gitolite3
chmod go+rx gitolite3

pushd /var/lib/gitolite3
rm -rf .git 
rm -f .gitignore
mkdir -p .gitolite/logs
chown gitolite3:gitolite3 .gitolite/logs
popd

popd

cp /usr/share/gitolite-backup-scripts/gitignore /var/lib/backup-gitolite/gitolite3/.gitignore
chown gitolite3:gitolite3 /var/lib/backup-gitolite/gitolite3/.gitignore
